language: node_js
notifications:
  email: false
node_js:
  - '10'
branches:
  only:
    - master
install:
  - npm ci
before_script:
  - npm prune
script:
  - npm run lint
  - npm test 
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: "$GH_TOKEN" # Set in travis-ci.org dashboard
  on:
    branch: master
